# Generated by Django 4.1.1 on 2022-10-11 11:35

from django.db import migrations, models
import eventex.subscriptions.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cpf',
            field=models.CharField(max_length=11, validators=[eventex.subscriptions.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('b6cb11d0-0c5a-40f5-9f0b-645a5054ec5f')),
        ),
    ]
