# Generated by Django 4.1.1 on 2022-10-18 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('68019a13-72d7-4091-9a98-19973c2404dc')),
        ),
    ]
