# Generated by Django 4.1.1 on 2022-10-18 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('27902547-97ca-45e6-bda0-bb9469f5106b')),
        ),
    ]
