# Generated by Django 4.1.2 on 2022-10-26 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('91f4a8d4-8608-4188-a126-956405c24a43')),
        ),
    ]
