# Generated by Django 4.1.2 on 2022-10-26 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('af1e0dea-b717-4218-b019-ce018aa806b1')),
        ),
    ]
