# Generated by Django 4.1.2 on 2022-10-28 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('70cfcbf1-3fa9-4571-998e-c80408377af2')),
        ),
    ]
