# Generated by Django 4.1.2 on 2022-11-03 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('5dc6250c-30a7-4ef7-acb4-462eaefa5fad')),
        ),
    ]
