# Generated by Django 4.1.2 on 2022-11-03 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscription_url_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url_identity',
            field=models.UUIDField(default=uuid.UUID('a5e5f181-2e18-463f-b48c-bd08a6990486')),
        ),
    ]
