# Generated by Django 4.1.2 on 2022-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
        migrations.AlterModelOptions(
            name='courseold',
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            }
        )
    ]
